"""init v1 gms tracking

Revision ID: 1664c43728fc
Revises: 
Create Date: 2026-01-29 08:57:00.302795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1664c43728fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uom', sa.String(length=32), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.Enum('sea', 'air', name='shipment_mode'), nullable=False),
    sa.Column('carrier', sa.String(length=128), nullable=True),
    sa.Column('tracking_ref', sa.String(length=128), nullable=True),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('booked', 'departed', 'in_transit', 'arrived', 'customs', 'out_for_delivery', 'delivered', name='shipment_status'), nullable=False),
    sa.Column('eta_initial', sa.Date(), nullable=True),
    sa.Column('eta_current', sa.Date(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_tracking_ref'), 'shipments', ['tracking_ref'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.CheckConstraint('lead_time_days >= 0', name='ck_supplier_lead_time_nonneg'),
    sa.CheckConstraint('reliability_score >= 0 AND reliability_score <= 100', name='ck_supplier_reliability_0_100'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('containers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('container_number', sa.String(length=16), nullable=False),
    sa.Column('seal_number', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_number', name='uq_container_number')
    )
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('warehouse', 'zone', 'dock', 'customs', 'quarantine', 'store', name='location_type'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_location_site_name')
    )
    op.create_table('shipment_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('event_code', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_events_ship_time', 'shipment_events', ['shipment_id', 'event_time'], unique=False)
    op.create_index(op.f('ix_shipment_events_shipment_id'), 'shipment_events', ['shipment_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'field', name='role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'shipped', 'partial', 'closed', 'cancelled', name='po_status'), nullable=False),
    sa.Column('expected_eta', sa.Date(), nullable=True),
    sa.Column('shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('stock_levels',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_on_hand', sa.Integer(), nullable=False),
    sa.Column('qty_reserved', sa.Integer(), nullable=False),
    sa.Column('qty_on_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('qty_on_hand >= 0', name='ck_stock_on_hand_nonneg'),
    sa.CheckConstraint('qty_on_order >= 0', name='ck_stock_on_order_nonneg'),
    sa.CheckConstraint('qty_reserved >= 0', name='ck_stock_reserved_nonneg'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'location_id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('from_location_id', sa.BigInteger(), nullable=True),
    sa.Column('to_location_id', sa.BigInteger(), nullable=True),
    sa.Column('movement_type', sa.Enum('receipt', 'issue', 'transfer', 'adjustment', 'scrap', 'reserve', 'unreserve', name='movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_stock_movement_qty_pos'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index('ix_stock_movements_product_time', 'stock_movements', ['product_id', 'happened_at'], unique=False)
    op.create_table('asn',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id')
    )
    op.create_table('goods_receipts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'posted', 'cancelled', name='receipt_status'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by', sa.BigInteger(), nullable=True),
    sa.Column('container_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_po_id'), 'goods_receipts', ['po_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('qty_ordered > 0', name='ck_po_line_qty_pos'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_po_line_unit_cost_nonneg'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('po_id', 'product_id')
    )
    op.create_table('goods_receipt_lines',
    sa.Column('receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('qty_damaged', sa.Integer(), nullable=False),
    sa.Column('lot_code', sa.String(length=64), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.CheckConstraint('qty_damaged >= 0', name='ck_gr_line_qty_damaged_nonneg'),
    sa.CheckConstraint('qty_received >= 0', name='ck_gr_line_qty_received_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('receipt_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_receipt_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_goods_receipts_po_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_table('asn')
    op.drop_index('ix_stock_movements_product_time', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('stock_levels')
    op.drop_table('purchase_orders')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index(op.f('ix_shipment_events_shipment_id'), table_name='shipment_events')
    op.drop_index('ix_shipment_events_ship_time', table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_table('locations')
    op.drop_table('containers')
    op.drop_table('suppliers')
    op.drop_table('sites')
    op.drop_index(op.f('ix_shipments_tracking_ref'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('products')
    # ### end Alembic commands ###
